### PR TITLE
Invert match - alt for #2

### PR DESCRIPTION
**Pull request by evs-chris**
Move matching to the open tag event so that text on non-matching nodes can be discarded. This is a potential alternate fix for #2.

### CODE REVIEW

**Comment by sheershoff** [comment]
ok, seems like this one doesn't leak. but my machine just hangs up on IO. i'll run just the XML parser without underlying saving to check for the leak.

**Comment by sheershoff** [comment]
3M xml nodes matched from a file of 10Gb. No signs of memory footprint constant growth. Haven't checked the heapdumps.

**Comment by evs-chris** [comment]
Cool. I'll go ahead and publish this then.

As for IO hanging, are you using the `done` callback in your callback e.g. `xos(xmlStream, '/some/path', function(node, done) { /* do stuff with node, wait on said stuff to finish, and then call */; done(); });`?  I would think that reading at least 1MB (maybe match fs block size if you can?) at a time and then making sure all processing is done before moving on to the next chunk would keep any IO starvation from occurring - at least any caused by disk thrashing anyways.

**Comment by sheershoff** [comment]
Yes, I use the callback. Thanks for pointing to that. I'll try to increase the chunk. However the xml parsing without writing to db goes ok. It's mariadb in the call stack. I tend to blame mariadb and strange VDS config. We'll move to another hosting soon anyway and I'll resetup the things.

**Pull request merged**
